apiVersion: apps/v1
kind: Deployment
metadata:
  name: uganda-egov-helpdesk
  labels:
    app: uganda-egov-helpdesk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uganda-egov-helpdesk
  template:
    metadata:
      labels:
        app: uganda-egov-helpdesk
    spec:
      containers:
      - name: app
        image: uganda-egov-helpdesk:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: google-cloud-project
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: twilio-auth-token
        - name: TWILIO_WHATSAPP_NUMBER
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: twilio-whatsapp-number
        - name: TWILIO_WEBHOOK_VERIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: twilio-webhook-verify-token
        - name: TWILIO_API_KEY_SID
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: twilio-api-key-sid
        # Legacy WhatsApp variables (can be removed after migration)
        # - name: WHATSAPP_ACCESS_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: whatsapp-secrets
        #       key: whatsapp-access-token
        # - name: WHATSAPP_PHONE_NUMBER_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: whatsapp-phone-number-id
        # - name: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: whatsapp-webhook-verify-token
        # - name: WHATSAPP_BUSINESS_ACCOUNT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: whatsapp-business-account-id
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: firebase-project-id
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: google-oauth-client-id
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: google-oauth-client-secret
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret-key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: encryption-key
        - name: ADMIN_WHATSAPP_GROUP
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: admin-whatsapp-group
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
      imagePullSecrets:
      - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: uganda-egov-helpdesk-service
spec:
  selector:
    app: uganda-egov-helpdesk
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uganda-egov-helpdesk-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.ugandaegov.com
    secretName: uganda-egov-tls
  rules:
  - host: api.ugandaegov.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uganda-egov-helpdesk-service
            port:
              number: 80